name = "text-to-image-ryden"
main = "index.js"  # Change to correct path if needed, e.g., "src/index.ts"
compatibility_date = "2024-05-01"

[vars]
HF_TOKEN = "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"
HF_MODEL = "stabilityai/stable-diffusion-2-1"
MODEL_NAME = "sd-3.5-large""
